### PR TITLE
Correct plugin to work with ST3.

### PR DESCRIPTION
**Pull request by Sheeprider**
Replace requests library with standard libraries.
Replace threading logic with direct calls.

Please note that this version is **ST3 ONLY**, you should probably have a different branch for ST3 if you intend to keep the ST2-compatible version.

Signed-off-by: Baptiste Millou baptiste@smoothie-creative.com

### CODE REVIEW

**Comment by pomeh** [comment]
Thanks for this port ! It's exactly what I was looking for.

But unfortunately, it does not works for me (I'm using ST3 build 3047). I've cloned & pulled your ST3 branch into my User packages folder & restarted Sublime Text 3:

```
$ git clone https://github.com/Sheeprider/Sublime-Csslisible.git
$ git checkout -b ST3 --track origin/ST3

$ git log -3 --oneline
76330cd Correct plugin to work with ST3.
36b6730 Merge pull request #4 from Darklg/patch-1
28fd255 Settings par défaut de CSSLisible.com
```

When I execute the command for the first time, I get this error message:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "c:\path\to\appdata\Sublime Text 3\Packages\Sublime-Csslisible\Csslisible.py", line 20, in run
    result = cssLisibleApiCall(original)
  File "c:\path\to\appdata\Sublime Text 3\Packages\Sublime-Csslisible\Csslisible.py", line 53, in cssLisibleApiCall
    conn = http.client.HTTPConnection(url.netloc, timeout=5)
  File "X/http/client.py", line 737, in __init__
  File "X/http/client.py", line 754, in _set_hostport
TypeError: Type str doesn't support the buffer API
```

I've no idea what's happening...

Then strangly, when I do a save on the "Csslisible.py" file without code modification, and try to run again the command, I get this error message

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "c:\path\to\appdata\Sublime Text 3\Packages\Sublime-Csslisible\Csslisible.py", line 20, in run
    result = cssLisibleApiCall(original)
  File "c:\path\to\appdata\Sublime Text 3\Packages\Sublime-Csslisible\Csslisible.py", line 54, in cssLisibleApiCall
    conn.request("POST", url.path, params, headers)
  File "X/http/client.py", line 1049, in request
  File "X/http/client.py", line 1087, in _send_request
  File "X/http/client.py", line 1045, in endheaders
  File "X/http/client.py", line 890, in _send_output
  File "X/http/client.py", line 828, in send
  File "X/http/client.py", line 806, in connect
  File "X/socket.py", line 424, in create_connection
  File "X/socket.py", line 415, in create_connection
socket.timeout: timed out
```

The connection is timed out because I'm behind a web proxy so I can't access to csslisible.com without this proxy. I've send you a PR to correct this at https://github.com/Sheeprider/Sublime-Csslisible/pull/1.

Then, it works very well, until I close & re-open ST when I get the first error message `TypeError: Type str doesn't support the buffer API`.

**Comment by Sheeprider** [comment]
This should fix the bug on first time execution, please let me know if it works for you.

**Comment by pomeh** [comment]
Yes, it works for me, thanks :)

**Comment by thierrylemoulec** [comment]
Merge in st3 branch

**Pull request closed without merging**
