### PR TITLE
added some usefull options

### PR DESCRIPTION
**Pull request by matiaspub**
"raccourcir_valeurs"
"selecteur_par_ligne"

### CODE REVIEW

**Comment by thierrylemoulec** [comment]
Thanks for the pull request, I added all the latest options from the API and updated the sublime-settings file and the readme.

**Comment by matiaspub** [comment]
Oooo, its cool. Thank you very much for the work.

**Comment by matiaspub** [comment]
Why so useful option "selecteur_par_ligne" was deleted from code?

**Comment by thierrylemoulec** [comment]
I just clean the options and use the official options from https://github.com/darklg/CSSLisible this way it's clear for everyone coming from the official csslisible to the ST2 plugin

**Pull request closed without merging**
